global:
  scrape_interval: 10s
  scrape_timeout: 5s

rule_files:

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'case_itau_api'
    static_configs:
      - targets: ['host.docker.internal:8090', 'host.docker.internal:8080']



