FROM mcr.microsoft.com/mssql/server:2017-latest-ubuntu

WORKDIR /usr/src/app

COPY . /usr/src/app
             
ENV SA_PASSWORD 7539514862Pp*
ENV ACCEPT_EULA Y
ENV MSSQL_PID Express

CMD /bin/bash ./entrypoint.sh